Testing TicTacToe methods for review.
CalyCherkaoui/Tic-Tac-Toe-Ruby pull request #1
Opened 2020-06-26 17:17 UTC by CalyCherkaoui

This pull-request is related to Testing Tic-Tac-Toe game methods.
The methods tested are : 
-  winner?
- grid_filled?
- pick_valid?
- not_picked?
- update_grid

2020-06-26 19:53 UTC, suretrust requested changes
Hi team, 👋 

### Great job thus far! 🙌 Please see my comments. 👇 

- [x] Add linter to your repo. You could check the [troubleshooting section of the linter guide repo](https://github.com/microverseinc/linters-config/blob/master/README.md#troubleshooting) to see if you're missing anything.

- [x] Add positive and negative scenarios for all tests as illustrated below.

**Kindly submit another CRR once these issues have been resolved.** _Happy coding!_ 🎉

2020-06-26 19:53 UTC, suretrust commented on spec/project_spec.rb
> +require './lib/board'
`require` should be used for external files, like gems, while `require_relative` should be used for referring to files within your directory.

2020-06-26 19:53 UTC, suretrust commented on spec/project_spec.rb
> +  end
- [ ] Your specs should cover positive and negative scenarios. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/Ruby_testing/commonsense.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59566098/)).

> In this example, you need to test with two arrays, one that's filled another that's not completely filled, then test as shown below (this is just an example implementing the positive and negative scenarios, you can do it anyhow you see fit).

```suggestion
  describe '#grid_filled?' do
    it 'returns true if grid is completely filled with strings' do
      expect(filled_test_board.grid_filled?).to eq(true)
    end
    
    it 'returns false if grid is not completely filled with strings' do
      expect(unfilled_test_board.grid_filled?).to eq(false)
    end
  end
```

2020-06-26 22:36 UTC, kobiyoyo requested changes
## Hi Team     ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, but there are a few more things required. 
### General
- [x] Lets write test for the initialize method in `Game` class
- [x] Lets test for  a draw scenario between players.
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-06-29 17:59 UTC, suretrust approved these changes
Hi team, 👋 

### Great job implementing the suggested changes. 💯 Let's get this merged! 👍 

- [x] You could check [better specs](http://www.betterspecs.org/) in your free time to check best `rspec` practices.

_Good luck with your future projects and happy coding!_ 🎉

2020-06-29 20:01 UTC, merged